### ISSUE TITLE
AutoInstall updates

### ISSUE THREAD

**Issue by Natio** [Natio/Places#18]
According to this stack overflow question http://stackoverflow.com/questions/4967669/android-install-apk-programmatically it doesn't seem too hard to implement automatic updates. We should discuss about it. I think it wold be great to have but it might become too hard to maintain and maybe it is not worth the effort needed to add it. Let me know your opinion.

**Comment by tehzhed** [comment]
I thought about automatic updates myself this afternoon. I think a very simple fix is the following: put major updates in a shared folder on Google Drive (so that a public link can be produced) and send push notifications to all our users telling them that a new version is available. Upon clicking on such notification, the user is prompted to the folder containing the .apk's where they can quickly download the latest version.

**Comment by Natio** [comment]
I like your idea

**Comment by tehzhed** [comment]
Implemented :) I created a Push channel called "Developers" so that we can try Push notifications without bothering users. You subscribe to this channel automatically upon running this version of Places for the first time. This means that when we release a new version of the code to the users, I'll just have to first comment out a line of code.
